# Generated by Django 2.2 on 2023-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20230601_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fee',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='', max_length=50),
        ),
    ]
