# Generated by Django 2.2 on 2023-06-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
