# Generated by Django 2.2 on 2023-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_checkout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
