# Generated by Django 2.2 on 2023-07-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_checkout_amountt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='amountt',
        ),
    ]
